/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper */

#ifndef _Included_headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper
#define _Included_headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper
 * Method:    createCubemapTexture
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_1DynamicCubemapCompositorWorkspaceNativeWrapper_createCubemapTexture
  (JNIEnv *, jclass);

/*
 * Class:     headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper
 * Method:    createCubemapCamera
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_1DynamicCubemapCompositorWorkspaceNativeWrapper_createCubemapCamera
  (JNIEnv *, jclass);

/*
 * Class:     headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper
 * Method:    createDynamicCubemapWorkspace
 * Signature: (JJJJLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_1DynamicCubemapCompositorWorkspaceNativeWrapper_createDynamicCubemapWorkspace
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jstring, jboolean);

/*
 * Class:     headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_DynamicCubemapCompositorWorkspaceNativeWrapper
 * Method:    addWorkspace
 * Signature: (JJJJLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_headwayent_hotshotengine_renderer_nativeinterface_classwrappers_ENG_1DynamicCubemapCompositorWorkspaceNativeWrapper_addWorkspace
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
