
/*
 * Created by Sebastian Bugiu on 4/9/23, 10:11 PM
 * sebastian.bugiu@headwayentertainment.net
 * Last modified 6/1/19, 10:18 PM
 * Copyright (c) 2023.
 * All rights reserved.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package headwayent.blackholedarksun.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int set_speed = 12;
  public static final int camera_attach_event = 48;
  public static final int look_at_pos = 45;
  public static final int light_specular_color = 24;
  public static final int STRING_LITERAL = 6;
  public static final int camera_detach_event = 49;
  public static final int exit = 56;
  public static final int play_sound_from_pos = 51;
  public static final int msecs = 40;
  public static final int ms = 42;
  public static final int look_at = 44;
  public static final int obj_def = 17;
  public static final int ai = 31;
  public static final int obj_event = 39;
  public static final int use_skybox_data_from_level = 11;
  public static final int spawn = 55;
  public static final int attach = 46;
  public static final int light_type = 21;
  public static final int BRACE_OPEN = 2;
  public static final int COMMA = 10;
  public static final int light_dir = 20;
  public static final int show_text = 53;
  public static final int health = 33;
  public static final int change_orientation = 15;
  public static final int show_text_pos = 54;
  public static final int CUTSCENE = 8;
  public static final int mesh = 26;
  public static final int orientation = 29;
  public static final int EOF = 0;
  public static final int camera_event = 43;
  public static final int error = 1;
  public static final int start_delay = 35;
  public static final int end_delay = 36;
  public static final int NUMBER = 4;
  public static final int pos = 37;
  public static final int light_diffuse_color = 23;
  public static final int position = 28;
  public static final int object = 38;
  public static final int ambient_light_upperhemi_lowerhemi_dir = 25;
  public static final int play_sound = 50;
  public static final int speed = 30;
  public static final int FLOAT = 7;
  public static final int play_sound_from_obj_pos = 52;
  public static final int change_position = 14;
  public static final int STRING = 5;
  public static final int friendly = 32;
  public static final int BRACE_CLOSE = 3;
  public static final int parallel_task = 18;
  public static final int skybox = 19;
  public static final int behavior = 34;
  public static final int light_power_scale = 22;
  public static final int INITIAL_CONDS = 9;
  public static final int completion_time = 16;
  public static final int change_speed = 13;
  public static final int detach = 47;
  public static final int secs = 41;
  public static final int type = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRACE_OPEN",
  "BRACE_CLOSE",
  "NUMBER",
  "STRING",
  "STRING_LITERAL",
  "FLOAT",
  "CUTSCENE",
  "INITIAL_CONDS",
  "COMMA",
  "use_skybox_data_from_level",
  "set_speed",
  "change_speed",
  "change_position",
  "change_orientation",
  "completion_time",
  "obj_def",
  "parallel_task",
  "skybox",
  "light_dir",
  "light_type",
  "light_power_scale",
  "light_diffuse_color",
  "light_specular_color",
  "ambient_light_upperhemi_lowerhemi_dir",
  "mesh",
  "type",
  "position",
  "orientation",
  "speed",
  "ai",
  "friendly",
  "health",
  "behavior",
  "start_delay",
  "end_delay",
  "pos",
  "object",
  "obj_event",
  "msecs",
  "secs",
  "ms",
  "camera_event",
  "look_at",
  "look_at_pos",
  "attach",
  "detach",
  "camera_attach_event",
  "camera_detach_event",
  "play_sound",
  "play_sound_from_pos",
  "play_sound_from_obj_pos",
  "show_text",
  "show_text_pos",
  "spawn",
  "exit"
  };
}

