//
// Created by sebas on 01.05.2017.
//

#ifndef BLACKHOLEDARKSUNONLINE4_HOTSHOTHUDMANAGER_H
#define BLACKHOLEDARKSUNONLINE4_HOTSHOTHUDMANAGER_H

namespace Hotshot {

}

#endif //BLACKHOLEDARKSUNONLINE4_HOTSHOTHUDMANAGER_H
